version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: libraryos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d libraryos"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: ./library-api
      dockerfile: Dockerfile
    environment:
      LIBRARYOS_DB_URL: jdbc:postgresql://postgres:5432/libraryos
      LIBRARYOS_DB_USER: admin
      LIBRARYOS_DB_PASSWORD: 123456
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data: