server:
  port: 8080

spring:
  datasource:
    url: ${LIBRARYOS_DB_URL:jdbc:postgresql://localhost:5432/libraryos}
    username: ${LIBRARYOS_DB_USER:admin}
    password: ${LIBRARYOS_DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.libraryos: INFO
    org.springframework.web: INFO